[[lemming.formatters]]
package = "black"
args = "-l 79 {path}"

[[lemming.formatters]]
package = "setup_cfg_fmt"
args = "--include-version-classifiers"

[[lemming.formatters]]
package = "isort"
args = "--profile black {path}"

[[lemming.linters]]
package = "flake8"
args = "--count --exclude *venv* --show-source --statistics --extend-ignore=W503,S101 --extend-exclude=example.py {path}"
also_install = ["flake8-bandit"]
