language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "nightly"
cache: pip
before_install:
  - python -m pip install --upgrade pip
install:
  - if [ -f requirements.txt ]; then pip install -U -r requirements.txt; fi
  - pip install -U flake8
script:
  - python -m flake8 --config .flake8
