language: python
os: Trusty
python:
  - "3.9"
cache: pip
before_install:
  - pip install -U pip
install:
  - if [ -f requirements.txt ]; then pip install -U -r requirements.txt; fi
  - pip install -U flake8
script:
  - python -m flake8 --count --show-source --statistics --ignore E501,E741,W291
