language: python
python:
  - "3.8"
  - "3.9"
cache: pip
before_install:
  - python -m pip install --upgrade pip
install:
  - if [ -f requirements.txt ]; then pip install -U -r requirements.txt; fi
  - if [ -f f8pl.txt ]; then pip install -U -r f8pl.txt || pip install -U -r f8pl.txt; fi
  - pip install -U flake8
script:
  - python -m flake8 --config .flake8
